/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = <String>[
    'pill_reminder',
    'health_monitor',
    'smart_home',
  ];
  static const String? _kFontPkg = null;

  static IconData pill_reminder =
      IconData(0xe800, fontFamily: _kFontFam[0], fontPackage: _kFontPkg);
  static IconData health_monitor =
      IconData(0xe800, fontFamily: _kFontFam[1], fontPackage: _kFontPkg);
  static IconData smart_home =
      IconData(0xe800, fontFamily: _kFontFam[2], fontPackage: _kFontPkg);
}
